// <auto-generated />
using System;
using CareerRoadmapGenerator.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CareerRoadmapGenerator.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251218082702_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CareerRoadmapGenerator.Models.Career", b =>
                {
                    b.Property<int>("CareerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CareerId"));

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Title")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("CareerId");

                    b.ToTable("Careers");
                });

            modelBuilder.Entity("CareerRoadmapGenerator.Models.ProjectIdea", b =>
                {
                    b.Property<int>("ProjectIdeaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectIdeaId"));

                    b.Property<int?>("CareerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Difficulty")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SkillId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("ProjectIdeaId");

                    b.HasIndex("CareerId");

                    b.HasIndex("SkillId");

                    b.ToTable("ProjectIdeas");
                });

            modelBuilder.Entity("CareerRoadmapGenerator.Models.Resource", b =>
                {
                    b.Property<int>("ResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResourceId"));

                    b.Property<int?>("CareerId")
                        .HasColumnType("int");

                    b.Property<int?>("SkillId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("ResourceId");

                    b.HasIndex("CareerId");

                    b.HasIndex("SkillId");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("CareerRoadmapGenerator.Models.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillId"));

                    b.Property<int?>("CareerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("Order")
                        .HasColumnType("int");

                    b.HasKey("SkillId");

                    b.HasIndex("CareerId");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("CareerRoadmapGenerator.Models.UserProgress", b =>
                {
                    b.Property<int>("UserProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserProgressId"));

                    b.Property<int?>("CareerId")
                        .HasColumnType("int");

                    b.Property<int?>("ProgressPercentage")
                        .HasColumnType("int");

                    b.Property<int?>("SkillId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserProgressId");

                    b.HasIndex("CareerId");

                    b.HasIndex("SkillId");

                    b.ToTable("UserProgresses");
                });

            modelBuilder.Entity("CareerRoadmapGenerator.Models.ProjectIdea", b =>
                {
                    b.HasOne("CareerRoadmapGenerator.Models.Career", "Career")
                        .WithMany("ProjectIdeas")
                        .HasForeignKey("CareerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CareerRoadmapGenerator.Models.Skill", "Skill")
                        .WithMany("ProjectIdeas")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Career");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("CareerRoadmapGenerator.Models.Resource", b =>
                {
                    b.HasOne("CareerRoadmapGenerator.Models.Career", "Career")
                        .WithMany("Resources")
                        .HasForeignKey("CareerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CareerRoadmapGenerator.Models.Skill", "Skill")
                        .WithMany("Resources")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Career");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("CareerRoadmapGenerator.Models.Skill", b =>
                {
                    b.HasOne("CareerRoadmapGenerator.Models.Career", "Career")
                        .WithMany("Skills")
                        .HasForeignKey("CareerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Career");
                });

            modelBuilder.Entity("CareerRoadmapGenerator.Models.UserProgress", b =>
                {
                    b.HasOne("CareerRoadmapGenerator.Models.Career", "Career")
                        .WithMany("UserProgresses")
                        .HasForeignKey("CareerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CareerRoadmapGenerator.Models.Skill", "Skill")
                        .WithMany("UserProgresses")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Career");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("CareerRoadmapGenerator.Models.Career", b =>
                {
                    b.Navigation("ProjectIdeas");

                    b.Navigation("Resources");

                    b.Navigation("Skills");

                    b.Navigation("UserProgresses");
                });

            modelBuilder.Entity("CareerRoadmapGenerator.Models.Skill", b =>
                {
                    b.Navigation("ProjectIdeas");

                    b.Navigation("Resources");

                    b.Navigation("UserProgresses");
                });
#pragma warning restore 612, 618
        }
    }
}
